name: CI Fuzz
on: [push, pull_request]
jobs:
  Fuzzing:
    runs-on: self-hosted
    steps:
    - name: Build Fuzzers
      uses: Marti2203/oss-fuzz/infra/cifuzz/actions/build_fuzzers@master
      with:
        oss-fuzz-project-name: 'c-blosc2'
        dry-run: false

    - name: Run Fuzzers
      uses: Marti2203/oss-fuzz/infra/cifuzz/actions/run_fuzzers@master
      with:
        oss-fuzz-project-name: 'c-blosc2'
        fuzz-seconds: 600
        dry-run: false

    - name: Upload Crash
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: artifacts
        path: ./out/artifacts
